name: hyp3-testing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  - gdal
  - hyp3_sdk>=1.1
  - jinja2
  - numpy
  - setuptools
  - setuptools_scm
  - pytest
  - pytest-cov
  - pytest-dependency
  - pytest-timeout
  - rasterio
  - wheel
  - xarray
  - pip:
      - s3pypi
