name: hyp3-testing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pip
  - gdal
  - hyp3_sdk>=2.1.1
  - jinja2
  - numpy
  - netCDF4  # provides xarray netCDF IO backend
  - setuptools
  - setuptools_scm
  - pytest
  - pytest-cov
  - pytest-dependency
  - pytest-timeout
  - rasterio
  - wheel
  - xarray
  - rioxarray
  - opencv<4.9.0  # https://github.com/conda-forge/opencv-feedstock/issues/400
  - pip:
      - remotezip
