name: hyp3-testing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  - gdal
  - hyp3_sdk>=1.3,<2
  - jinja2
  - numpy
  - netCDF4  # provides xarray netCDF IO backend
  - setuptools
  - setuptools_scm
  - pytest
  - pytest-cov
  - pytest-dependency
  - pytest-timeout
  - rasterio
  - wheel
  - xarray
  - rioxarray
  - pip:
      - remotezip
