[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.pytest.ini_options]
markers = [
    "nameskip: skip these tests when name provided",
    "golden: golden comparison tests"
]

[project]
name = "hyp3_testing"
requires-python = ">=3.10"
description = "HyP3 plugin for testing processing"
license = {text = "BSD-3-Clause"}
authors = [
    {name="ASF Tools Team", email="UAF-asf-apd@alaska.edu"}
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "hyp3_sdk>=2.1.1",
    "jinja2",
    "numpy",
    "netCDF4",  # provides xarray netCDF IO backend
    "rasterio",
    "xarray",
]
dynamic = ["version", "readme"]

[project.optional-dependencies]
develop = [
    "pytest",
    "pytest-cov",
    "pytest-dependency",
    "pytest-timeout",
]

[project.urls]
Homepage = "https://github.com/ASFHyP3/hyp3-testing"
Documentation = "https://hyp3-docs.asf.alaska.edu"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools_scm]

[tool.ruff]
line-length = 120
# The directories to consider when resolving first- vs. third-party imports.
# See: https://docs.astral.sh/ruff/settings/#src
src = [".", "tests"]

[tool.ruff.format]
indent-style = "space"
quote-style = "single"

[tool.ruff.lint]
extend-select = [
    "I",   # isort: https://docs.astral.sh/ruff/rules/#isort-i

    # TODO: uncomment the following extensions and address their warnings:
    #"UP",  # pyupgrade: https://docs.astral.sh/ruff/rules/#pyupgrade-up
    #"D",   # pydocstyle: https://docs.astral.sh/ruff/rules/#pydocstyle-d
    #"ANN", # annotations: https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    #"PTH", # use-pathlib-pth: https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
case-sensitive = true
lines-after-imports = 2

[tool.mypy]
python_version = "3.10"
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true
check_untyped_defs = true
