name: Golden autoRIFT

on:
  workflow_dispatch:
    inputs:
      submission_template:
        description: 'Name of the submission template to use'
        required: true
        type: choice
        options:
          - autorift_golden.json.j2
          - autorift_its_live_golden.json.j2

jobs:
  golden:
    runs-on: ubuntu-24.04-arm # TODO: revert to ubuntu-latest after fixing https://github.com/ASFHyP3/hyp3-testing/issues/128
    steps:
      - uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: Pytest in conda environment
        env:
          EARTHDATA_LOGIN_USER: ${{ secrets.EARTHDATA_LOGIN_USER }}
          EARTHDATA_LOGIN_PASSWORD: ${{ secrets.EARTHDATA_LOGIN_PASSWORD }}
          HYP3_TESTING_SUBMISSION_TEMPLATE: ${{ inputs.submission_template }}
        shell: bash -l {0}
        run: |
          python -m pip install .[develop]
          pytest -s tests/test_autorift.py
