name: Golden TIFs

on:
  workflow_dispatch:
    inputs:
      process:
        description: "Select a supported process: rtc, insar"
        required: true


jobs:
  golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: hyp3-testing
          environment-file: conda-env.yml

      - name: Pytest in conda environment
        env:
          EARTHDATA_LOGIN_USER: ${{ secrets.EARTHDATA_LOGIN_USER }}
          EARTHDATA_LOGIN_PASSWORD: ${{ secrets.EARTHDATA_LOGIN_PASSWORD }}
        shell: bash -l {0}
        run: |
          python -m pip install .[develop]
          pytest -s --process ${{ github.event.inputs.process }} tests/test_tifs.py
