name: Test and tag

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: 3.8
          activate-environment: hyp3-testing
          environment-file: environment.yml

      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install .[develop]
          pytest --cov=hyp3_testing -m "not golden"


  tag_version:
    if: github.ref == 'refs/heads/main'
    needs: pytest
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@main
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
